### ISSUE TITLE
Checklist for final release

### ISSUE THREAD

**Issue by Fa1lx** [Fa1lx/epicseven_gear#11]
- [x] Json Decoding working
- [x] UI looks tasty
- [x] Damage and Stat Calculation works
